/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: '#0b1326',
        'on-primary': '#002e6a',
        'on-tertiary-container': '#003111',
        'on-tertiary': '#003915',
        'on-error': '#690005',
        'on-secondary': '#233144',
        'outline-variant': '#424754',
        primary: '#adc6ff',
        'primary-container': '#4d8eff',
        'surface-variant': '#2d3449',
        tertiary: '#4ae176',
        'tertiary-container': '#00a74b',
        surface: '#0b1326',
        'surface-dim': '#0b1326',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-bright': '#31394d',
        'surface-tint': '#adc6ff',
        secondary: '#b9c7df',
        'secondary-container': '#3c4a5e',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#c2c6d6',
        'on-background': '#dae2fd',
        'on-primary-container': '#00285d',
        'on-secondary-container': '#abb9d1',
        'inverse-surface': '#dae2fd',
        'inverse-primary': '#005ac2',
        'inverse-on-surface': '#283044',
        outline: '#8c909f',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
